[versions]
androidGradlePlugin = "8.1.0"
kotlin = "1.7.20"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


